### ISSUE TITLE
Serialize observables

### ISSUE THREAD

**Issue by martijndwars** [MartijnDwars/RxSpark#1]
Observables are not serialisable. We currently hardcoded the observable (`Main.clock`) and the wrapper. Find nice solution.

**Comment by martijndwars** [comment]
In hindsight, I'm not sure if this is the correct approach. A `Receiver` in Spark is supposed to be able to run on worker nodes and to receive external data. I cannot think of a use case in which serialising an observable would make much sense.

I think we should shift our focus to making the output of Spark observable, instead of using observables as a data source.

**Comment by nspruit** [comment]
So, you don't think it's possible to use an observable as data source? Maybe we can achieve that without serializing it

**Comment by martijndwars** [comment]
I don't think it's impossible, but I think it requires a different approach. Assume we use an observable as data source. Now imagine several worker nodes. Those workers need to connect to the data source to obtain data. Then we need some kind of observable that emits events over the network. This needs some more thinking before we can actually implement it (no idea if it i even possible, but it sounds exciting?)

**Comment by nspruit** [comment]
Alright, then we'll leave this issue closed for a while and focus on the 'output' side first.
