### ISSUE TITLE
Generic observables

### ISSUE THREAD

**Issue by martijndwars** [MartijnDwars/RxSpark#2]
Currently, hardcoded `Long`. Use generics.

**Comment by martijndwars** [comment]
I'm currently trying to fix this.

**Comment by nspruit** [comment]
I see you have been able to fix this issue as well as issue #3? If that's the case, could you please put your changes in a pull request when your finished? Then I'll check your changes and merge them afterwards. After that I'll start working on #1

**Comment by nspruit** [comment]
Closing, see #1
