### ISSUE TITLE
Observable output

### ISSUE THREAD

**Issue by martijndwars** [MartijnDwars/RxSpark#4]
I created this issue for discussing the the output side. Intuitively, I thought the following piece of code would kind of do the trick:

```
val lines = ssc.socketTextStream("localhost", 9999, StorageLevel.MEMORY_AND_DISK_SER)
val words = lines.flatMap(_.split(" "))
val wordCounts = words.map(x => (x, 1)).reduceByKey(_ + _)

val o = Observable[(String, Int)](subscriber => {
  wordCounts.foreachRDD((x: RDD[(String, Int)]) =>
    x.foreach((y: (String, Int)) =>
      subscriber.onNext(y) // Spark serializes this closure, but subscriber is not serializable, grr..
    )
  )

  subscriber.onCompleted()
})
```

The idea was to iterate through the DStream (using `foreachRDD`), then iterate through the items inside of the RDD (using `foreach`) and then emit those items. However, Spark serializes the closure and the Subscriber class is not serializable.

Perhaps you can use this as a starting point, @nspruit?

**Comment by nspruit** [comment]
I'll look into it, probably not today however

**Comment by nspruit** [comment]
I guess this issue can be closed, as we already have a helper method that transforms a DStream into an Observable
